/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.senai.sc.sistema_gestao;

import br.senai.sc.sistema_gestao.views.CadastroColaborador;
import br.senai.sc.sistema_gestao.views.EdicaoCadastroColaborador;
import br.senai.sc.sistema_gestao.views.TelaPadrao;
import java.awt.CardLayout;
import static java.awt.Frame.MAXIMIZED_BOTH;

/**
 *
 * @author Aluno
 */
public class TelaLoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form Colaborador
     */
    public TelaLoginFrame() {
        initComponents();
        
        TelaPadrao tp = new TelaPadrao();
        CadastroColaborador cadCol = new CadastroColaborador();
        EdicaoCadastroColaborador lisCol = new EdicaoCadastroColaborador();
        
        painelPrincipal.add(cadCol, "cadastroColaborador");
        painelPrincipal.add(tp, "telaPadrao");
        painelPrincipal.add(lisCol, "listagemColaborador");
        
        //Chamar a tela padrão aqui
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "telaPadrao");
        
        this.setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        barraDeMenu = new javax.swing.JMenuBar();
        menuColaborador = new javax.swing.JMenu();
        menCadastrarColaborador = new javax.swing.JMenuItem();
        menListarColaborador = new javax.swing.JMenuItem();
        menuEquipe = new javax.swing.JMenu();
        menCadastrarEquipe = new javax.swing.JMenuItem();
        menListarEquipe = new javax.swing.JMenuItem();
        menuAgenda = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuTarefa = new javax.swing.JMenu();
        menAdicionarTarefa = new javax.swing.JMenuItem();
        menEditarTarefa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setLayout(new java.awt.CardLayout());

        menuColaborador.setText("Colaborador");

        menCadastrarColaborador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        menCadastrarColaborador.setText("Cadastrar");
        menCadastrarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadastrarColaboradorActionPerformed(evt);
            }
        });
        menuColaborador.add(menCadastrarColaborador);

        menListarColaborador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menListarColaborador.setText("Listar");
        menListarColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListarColaboradorActionPerformed(evt);
            }
        });
        menuColaborador.add(menListarColaborador);

        barraDeMenu.add(menuColaborador);

        menuEquipe.setText("Equipe");

        menCadastrarEquipe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        menCadastrarEquipe.setText("Cadastrar");
        menuEquipe.add(menCadastrarEquipe);

        menListarEquipe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menListarEquipe.setText("Listar");
        menListarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menListarEquipeActionPerformed(evt);
            }
        });
        menuEquipe.add(menListarEquipe);

        barraDeMenu.add(menuEquipe);

        menuAgenda.setText("Agenda");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem5.setText("Ver agenda do colaborador");
        menuAgenda.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        jMenuItem6.setText("Ver agenda da equipe");
        menuAgenda.add(jMenuItem6);

        barraDeMenu.add(menuAgenda);

        menuTarefa.setText("Tarefa");

        menAdicionarTarefa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        menAdicionarTarefa.setText("Adicionar");
        menuTarefa.add(menAdicionarTarefa);

        menEditarTarefa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        menEditarTarefa.setText("Editar");
        menuTarefa.add(menEditarTarefa);

        barraDeMenu.add(menuTarefa);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menCadastrarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadastrarColaboradorActionPerformed
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, "cadastroColaborador");
    }//GEN-LAST:event_menCadastrarColaboradorActionPerformed

    private void menListarColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListarColaboradorActionPerformed
        
        
    }//GEN-LAST:event_menListarColaboradorActionPerformed

    private void menListarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menListarEquipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menListarEquipeActionPerformed

    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem menAdicionarTarefa;
    private javax.swing.JMenuItem menCadastrarColaborador;
    private javax.swing.JMenuItem menCadastrarEquipe;
    private javax.swing.JMenuItem menEditarTarefa;
    private javax.swing.JMenuItem menListarColaborador;
    private javax.swing.JMenuItem menListarEquipe;
    private javax.swing.JMenu menuAgenda;
    private javax.swing.JMenu menuColaborador;
    private javax.swing.JMenu menuEquipe;
    private javax.swing.JMenu menuTarefa;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
